brain/CODE/Brain Tumor Detection/Brain Tumor Detection/BrainTumorDetection/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from . import views as mainView
from users import views as usr
from admins import views as admins

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainView.index, name='index'),
    path("index/", mainView.index, name="index"),
    path("logout/", mainView.logout, name="logout"),
    path("UserLogin/", mainView.UserLogin, name="UserLogin"),
    path("AdminLogin/", mainView.AdminLogin, name="AdminLogin"),
    path("UserRegister/", mainView.UserRegister, name="UserRegister"),

    ### User Side Views
    path("UserRegisterActions/", usr.UserRegisterActions, name="UserRegisterActions"),
    path("UserLoginCheck/", usr.UserLoginCheck, name="UserLoginCheck"),
    path("UserHome/", usr.UserHome, name="UserHome"),
    path("UserDetect/", usr.UserDetect, name="UserDetect"),
    path("UserTraining/", usr.UserTraining, name="UserTraining"),




    ### Admin Side Views
    path("AdminLoginCheck/", admins.AdminLoginCheck, name="AdminLoginCheck"),
    path("ViewRegisteredUsers/", admins.ViewRegisteredUsers, name="ViewRegisteredUsers"),
    path("AdminActivaUsers/", admins.AdminActivaUsers, name="AdminActivaUsers"),
    path("AdminHome/", admins.AdminHome, name="AdminHome"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

brain/CODE/Brain Tumor Detection/Brain Tumor Detection/users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                           required=True, max_length=100)

    loginid = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                              required=True, max_length=100)

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}', 'class': 'form-control',
                                          'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters'}),
        required=True, max_length=100)

    mobile = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[56789][0-9]{9}', 'class': 'form-control'}),
                             required=True,
                             max_length=100)

    email = forms.CharField(
        widget=forms.TextInput(attrs={'pattern': '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$', 'class': 'form-control'}),
        required=True, max_length=100)

    locality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, max_length=100)

    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols':22, 'class': 'form-control'}),
                              required=True, max_length=250)

    city = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    state = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    status = forms.CharField(widget=forms.HiddenInput(), initial='waiting', max_length=100)

    class Meta():
        model = UserRegistrationModel
        fields = '__all__'

brain/CODE/Brain Tumor Detection/Brain Tumor Detection/assets/templates/AdminLogin.html
{% extends  'base.html' %}
{% load static %}

{% block title %}
    Admin Login
{% endblock %}
{% block admin_login %}
    active
{% endblock %}


{% block content %}
    <style>
        .jumbotron {
            font-family: "Book Antiqua";
            background: white;
            margin-top: 100px;
        }
    </style>

    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="card card-header col-md-6">
                <h2 class="text-center p-2" style="font-family: 'Book Antiqua'">Admin Login</h2>

                <form action="{% url 'AdminLoginCheck' %}" method="POST" class="text-primary">
                    {% csrf_token %}

                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="text" class="form-control" name="loginid" required
                                   placeholder="Enter Login Id">
                        </div>
                    </div>
                    <br>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="password" class="form-control" name="pswd" required
                                   placeholder="Enter password">
                        </div>
                    </div>
                    <br>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <center>
                                <input type="submit" class="btn btn-primary">
                                <input type="reset" class="mx-2 btn btn-outline-dark">
                            </center>
                        </div>
                    </div>


                    <!-- Message -->
                    {% if messages %}
                        {% for message in messages %}
                            <p align="center" class="text-primary"> {{ message }}</p>
                        {% endfor %}
                    {% endif %}


                </form>
            </div>
        </div>
    </div>
    <br>
{% endblock %}

brain/CODE/Brain Tumor Detection/Brain Tumor Detection/assets/templates/UserLogin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Login{% endblock %}
{% block user_login %}active{% endblock %}

{% block content %}
    <style>
        .jumbotron {
            font-family: "Book Antiqua";
            background: white;
            margin-top: 100px;
        }
    </style>

    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="card card-header col-md-6">
                <h2 class="text-center p-2" style="font-family: 'Book Antiqua'">User Login</h2>
                <form action="{% url 'UserLoginCheck' %}" method="POST" class="text-primary">
                    {% csrf_token %}

                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="text" class="form-control" name="loginname" required
                                   placeholder="Enter Login Id">
                        </div>
                    </div>
                    <br>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="password" class="form-control" name="pswd" required
                                   placeholder="Enter password">
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <br>
                            <center>
                                <input type="submit" class="btn btn-primary">
                                <input type="reset" class="mx-2 btn btn-outline-dark">
                            </center>
                        </div>
                    </div>


                    <!-- Message -->
                    {% if messages %}
                        {% for message in messages %}
                            <p align="center" class="text-primary"> {{ message }}</p>
                        {% endfor %}
                    {% endif %}

                </form>
            </div>
        </div>
    </div>
    <br>
{% endblock %}

brain/CODE/Brain Tumor Detection/Brain Tumor Detection/assets/templates/UserRegistrations.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .jumbotron {
            margin-top: 100px;
            font-family: "Book Antiqua";
            text-align: center;
            background: white;
        }

        h2 {
            font-family: "Book Antiqua";
        }

        .row {
            background: #f7f7f7;
        }
    </style>


    <!--form -->

    <div class="jumbotron">

        <div class="container">
            <center>
                <div class="row card card-body" style="background-color:#f7f7f7;">
                    <form action="{% url 'UserRegisterActions' %}" method="POST">

                        {% csrf_token %}
                        <h2 align="center"><strong>User Sign up</strong></h2>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="id_name">User Name</label>
                                {{ form.name }}
                            </div>

                            <div class="form-group col-md-4">
                                <label for="id_loginid">Login Id</label>
                                {{ form.loginid }}
                            </div>


                            <div class="form-group col-md-4">
                                <label for="id_email">Email</label>
                                {{ form.email }}
                            </div>

                            <div class="form-group col-md-4">
                                <label for="id_mobile">Mobile</label>
                                {{ form.mobile }}
                            </div>


                            <div class="form-group col-md-4">
                                <label for="id_password">Password</label>
                                {{ form.password }}
                            </div>


                            <div class="form-group col-md-4">
                                <label for="id_locality">Locality</label>
                                {{ form.locality }}
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="id_city">City</label>
                                {{ form.city }}
                            </div>

                            <div class="form-group col-md-4">

                            </div>
                            <div class="form-group col-md-4">
                                <label for="id_state">State</label>
                                {{ form.state }}
                            </div>
                            <div class="form-group col-md-3">

                                {{ form.status }}
                            </div>


                            <div class="form-group col-md-6">
                                <label for="id_address">Address </label>
                                {{ form.address }}

                            </div>
                            <br>

                        </div>


                        <button type="submit" class="btn btn-primary">Sign in</button>
                        <button type="reset" class="btn btn-outline-dark mx-2">Reset</button>
                        <!-- Message -->
                        {% if messages %}
                            {% for message in messages %}
                                <p align="center" class="text-primary"> {{ message }}</p>
                            {% endfor %}
                        {% endif %}

                    </form>
                </div>
            </center>
        </div>

    </div>

    <br>



{% endblock %}

brain/CODE/Brain Tumor Detection/Brain Tumor Detection/assets/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} {% endblock %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
            href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
            rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Green - v4.5.0
    * Template URL: https://bootstrapmade.com/green-free-one-page-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/4.3.1/css/bootstrap.min.css' %}">

</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center">

        <h1 class="logo me-auto"><a href="/">Machine Learning</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto {% block home %} {% endblock %}" href="/">Home</a></li>
                <li><a class="nav-link scrollto {% block user_login %} {% endblock %}"
                       href="{% url 'UserLogin' %}">User</a></li>
                <li><a class="nav-link scrollto {% block admin_login %} {% endblock %}" href="{% url 'AdminLogin' %}">Admin</a>
                </li>
                <li><a class="getstarted scrollto" href="{% url 'UserRegister' %}">Register</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

{% block content %}

{% endblock %}

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Green</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/green-free-one-page-bootstrap-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
<script src="{% static  'vendor/swiper/swiper-bundle.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

brain/CODE/Brain Tumor Detection/Brain Tumor Detection/assets/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Brain Tumor Detection
{% endblock %}

{% block home %}active{% endblock %}

{% block content %}
    <!-- ======= Hero Section ======= -->
    <section id="hero">
        <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

            <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

            <div class="carousel-inner" role="listbox">

                <!-- Slide 1 -->
                <div class="carousel-item active" style="background-image: url({% static 'img/slide/slide-1.jpg' %})">
                    <div class="carousel-container">
                        <div class="container">
                            <h2 class="animate__animated animate__fadeInDown">
                                A Comparative Study of Deep Neural Networks for the Detection of Brain Tumors
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
            </a>

            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
            </a>

        </div>
    </section><!-- End Hero -->

    <main id="main">

        <!-- ======= Featured Services Section ======= -->
        <section id="featured-services" class="featured-services section-bg">
            <div class="container">

                <div class="row no-gutters">
                    <div class="col-lg-4 col-md-6">
                       
                    </div>
                    <div class="col-lg-4 col-md-6">
                           
                        </div>
                    
                
                    </div>
                    <div class="col-lg-4 col-md-6">
                        
                           
                        </div>
                    </div>
                </div>

            </div>
        </section>
        <!-- End Featured Services Section -->
    </main>
    <!-- End #main -->
{% endblock %}